@backend_HostAddress = http://localhost:5172


@search=string
GET {{backend_HostAddress}}/api/fooditem?search={{search}}

###

@code=string
GET {{backend_HostAddress}}/api/fooditem/{{code}}/components

###
