import { FoodItemSchemaType } from '@/models/schemas/zod/food-item-schema'

export const foodItems: FoodItemSchemaType[] = [
  {
    code: 'BRC0001C',
    name: 'Abacate, polpa, in natura, Brasil',
    scientificName: 'Persea americana Mill',
    group: 'Frutas e derivados',
    brand: 'Genérico',
    components: [
      {
        id: '1',
        unit: 'g',
        foodItemCode: 'BRC0001C',
        name: 'Carboidratos',
        dataCount: 15,
      },
      {
        id: '2',
        unit: 'g',
        foodItemCode: 'BRC0001C',
        name: 'Proteínas',
        dataCount: 2,
      },
      {
        id: '3',
        unit: 'g',
        foodItemCode: 'BRC0001C',
        name: 'Gorduras',
        dataCount: 10,
      },
    ],
  },
  {
    code: 'BRC0195C',
    name: 'Abacaxi, cozido, caramelado',
    scientificName: 'Ananas comosus',
    group: 'Frutas e derivados',
    brand: 'Genérico',
    components: [
      {
        id: '4',
        unit: 'g',
        foodItemCode: 'BRC0195C',
        name: 'Carboidratos',
        dataCount: 20,
      },
      {
        id: '5',
        unit: 'g',
        foodItemCode: 'BRC0195C',
        name: 'Proteínas',
        dataCount: 1,
      },
      {
        id: '6',
        unit: 'g',
        foodItemCode: 'BRC0195C',
        name: 'Fibras',
        dataCount: 3,
      },
    ],
  },
  {
    code: 'BRC0300C',
    name: 'Abacaxi, grelhado, c/ cobertura de chocolate',
    scientificName: 'Ananas comosus',
    group: 'Frutas e derivados',
    brand: 'Genérico',
    components: [
      {
        id: '7',
        unit: 'g',
        foodItemCode: 'BRC0300C',
        name: 'Carboidratos',
        dataCount: 25,
      },
      {
        id: '8',
        unit: 'g',
        foodItemCode: 'BRC0300C',
        name: 'Gorduras',
        dataCount: 8,
      },
      {
        id: '9',
        unit: 'g',
        foodItemCode: 'BRC0300C',
        name: 'Proteínas',
        dataCount: 2,
      },
    ],
  },
  {
    code: 'BRC0054C',
    name: 'Abacaxi, polpa, congelada, Brasil',
    scientificName: 'Ananas comosus L.',
    group: 'Frutas e derivados',
    brand: 'Genérico',
    components: [
      {
        id: '10',
        unit: 'g',
        foodItemCode: 'BRC0054C',
        name: 'Carboidratos',
        dataCount: 12,
      },
      {
        id: '11',
        unit: 'g',
        foodItemCode: 'BRC0054C',
        name: 'Água',
        dataCount: 85,
      },
    ],
  },
  {
    code: 'BRC0264C',
    name: 'Abacaxi, polpa, desidratada, Brasil',
    scientificName: 'Ananas comosus',
    group: 'Frutas e derivados',
    brand: 'Genérico',
    components: [
      {
        id: '12',
        unit: 'g',
        foodItemCode: 'BRC0264C',
        name: 'Carboidratos',
        dataCount: 50,
      },
      {
        id: '13',
        unit: 'g',
        foodItemCode: 'BRC0264C',
        name: 'Fibras',
        dataCount: 5,
      },
      {
        id: '14',
        unit: 'g',
        foodItemCode: 'BRC0264C',
        name: 'Proteínas',
        dataCount: 1,
      },
    ],
  },
  {
    code: 'BRC0069C',
    name: 'Abiu, in natura, Brasil',
    scientificName: 'Lucuma caimito (Ruiz & Pav.) Roem & Schult',
    group: 'Frutas e derivados',
    brand: 'Genérico',
    components: [
      {
        id: '15',
        unit: 'g',
        foodItemCode: 'BRC0069C',
        name: 'Carboidratos',
        dataCount: 14,
      },
      {
        id: '16',
        unit: 'g',
        foodItemCode: 'BRC0069C',
        name: 'Gorduras',
        dataCount: 3,
      },
      {
        id: '17',
        unit: 'g',
        foodItemCode: 'BRC0069C',
        name: 'Proteínas',
        dataCount: 1,
      },
    ],
  },
  {
    code: 'BRC0002B',
    name: 'Abóbora, cabotian (japonesa), s/ casca, s/sementes, crua, Brasil',
    scientificName: 'Cucurbita maxima x Cucurbita moschata',
    group: 'Vegetais e derivados',
    brand: 'Genérico',
    components: [
      {
        id: '18',
        unit: 'g',
        foodItemCode: 'BRC0002B',
        name: 'Carboidratos',
        dataCount: 7,
      },
      {
        id: '19',
        unit: 'g',
        foodItemCode: 'BRC0002B',
        name: 'Fibras',
        dataCount: 2,
      },
      {
        id: '20',
        unit: 'g',
        foodItemCode: 'BRC0002B',
        name: 'Água',
        dataCount: 89,
      },
    ],
  },
  {
    code: 'BRC0003B',
    name: 'Abóbora, menina brasileira, s/ casca, s/ sementes, crua, Brasil',
    scientificName: 'Cucurbita moschata',
    group: 'Vegetais e derivados',
    brand: 'Genérico',
    components: [
      {
        id: '21',
        unit: 'g',
        foodItemCode: 'BRC0003B',
        name: 'Carboidratos',
        dataCount: 6,
      },
      {
        id: '22',
        unit: 'g',
        foodItemCode: 'BRC0003B',
        name: 'Fibras',
        dataCount: 2,
      },
      {
        id: '23',
        unit: 'g',
        foodItemCode: 'BRC0003B',
        name: 'Água',
        dataCount: 90,
      },
    ],
  },
  {
    code: 'BRC0355B',
    name: 'Abóbora, moranga, s/ casca, s/ semente, assada, s/ óleo, c/ sal, Brasil',
    scientificName: 'Cucurbita pepo L.',
    group: 'Vegetais e derivados',
    brand: 'Genérico',
    components: [
      {
        id: '24',
        unit: 'g',
        foodItemCode: 'BRC0355B',
        name: 'Carboidratos',
        dataCount: 8,
      },
      {
        id: '25',
        unit: 'g',
        foodItemCode: 'BRC0355B',
        name: 'Fibras',
        dataCount: 3,
      },
      {
        id: '26',
        unit: 'g',
        foodItemCode: 'BRC0355B',
        name: 'Água',
        dataCount: 88,
      },
    ],
  },
]
